# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18dFyUprvAkfxSAHuS30hCg05OfcC0KVI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns\

